# Generated by Django 3.2.16 on 2022-12-21 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20221220_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique shopping cart',
        ),
    ]
