# Generated by Django 3.2.16 on 2022-12-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221221_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='backend-media/', verbose_name='Изображение'),
        ),
    ]
