# Generated by Django 3.2.16 on 2022-12-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20221222_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipe/', verbose_name='Изображение'),
        ),
    ]
